# Generated by Django 6.0.5 on 2026-05-08 17:02
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        TrigramExtension(),
    ]
